# Generated by Django 4.0.4 on 2022-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0003_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('keywords', models.CharField(max_length=260)),
                ('text', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('img_data', models.CharField(max_length=20)),
            ],
        ),
    ]
