# Generated by Django 4.0.4 on 2022-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0004_articles_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='keywords',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
