# Generated by Django 4.0.4 on 2022-06-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0005_alter_articles_keywords_alter_articles_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='img_data',
        ),
    ]
