# Generated by Django 4.0.4 on 2022-06-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0006_remove_pages_img_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
