# Generated by Django 4.0.4 on 2022-06-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0007_alter_articles_slug_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
