# Generated by Django 4.0.4 on 2022-06-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0008_pages_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='keywords',
            field=models.CharField(default='', max_length=260),
        ),
    ]
