# Generated by Django 4.0.4 on 2022-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0009_alter_articles_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='keywords_ru',
            field=models.CharField(default='', max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='keywords_uk',
            field=models.CharField(default='', max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_uk',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='message_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_uk',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_text_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_text_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_uk',
            field=models.TextField(null=True),
        ),
    ]
