# Generated by Django 4.0.4 on 2022-06-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0011_alter_service_text_alter_service_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='text_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='text_uk',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
