# Generated by Django 4.0.4 on 2022-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0012_alter_service_text_alter_service_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_uk',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
