# Generated by Django 4.0.4 on 2022-06-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0013_alter_service_name_alter_service_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short_text',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_text_ru',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_text_uk',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
