# Generated by Django 4.0.4 on 2022-06-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0014_alter_service_short_text_alter_service_short_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='description',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
        migrations.AddField(
            model_name='pages',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='description_uk',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
        migrations.AddField(
            model_name='pages',
            name='keywords_ru',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='keywords_uk',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
    ]
