# Generated by Django 4.0.4 on 2022-06-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0016_pages_text_pages_text_ru_pages_text_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='img_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
