# Generated by Django 4.0.4 on 2022-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0017_pages_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
        migrations.AddField(
            model_name='service',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
    ]
