# Generated by Django 4.0.4 on 2022-06-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0018_service_description_service_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
    ]
