# Generated by Django 4.0.4 on 2022-06-17 08:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0020_alter_articles_text_alter_articles_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pages',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='text_uk',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='message_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='message_uk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='text_uk',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
