# Generated by Django 4.0.4 on 2022-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0021_alter_pages_text_alter_pages_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='message_uk',
            field=models.TextField(null=True),
        ),
    ]
